name = "freeducation"
main = "src/index.ts"
compatibility_date = "2025-12-29"

# D1 Database Binding
[[d1_databases]]
binding = "DB"
database_name = "freeducation"
database_id = "aa5d06f3-d769-405c-85e5-0de29118e1d1"


# R2 Bucket Binding
[[r2_buckets]]
binding = "BUCKET"
bucket_name = "freeducation"

# Vars for security (You should set these in Cloudflare Dashboard too)
[vars]
JWT_SECRET = "change-this-secret-to-something-long-and-random"
