name = "freeducation"



[[d1_databases]]
binding = "DB"
database_name = "freeducation"
database_id = "f2bd4fc8-dc5d-4a0d-8539-e18b1925de25"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "freeducation"



[vars]
GMAIL_CLIENT_ID = "151296843802-ansdm59387uk2r0lfaebvkr5566beq3g.apps.googleusercontent.com"
GMAIL_CLIENT_SECRET = "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"
GMAIL_REFRESH_TOKEN = "1//047Rxk_CAUUvpCgYIARAAGAQSNwF-L9Iro5UdL91EkNaDDzfXpc9_7i4ZiA4bqe2YxK7gtZ76sC36W16yYkylDysJGKcn9fnWRaM"
