import { PROFILE_SCRIPT_POSTS_FEED_LOAD } from "./feedLoad.js";
import { PROFILE_SCRIPT_POSTS_INTERACTIONS } from "./interactions.js";
import { PROFILE_SCRIPT_POSTS_RENDER_AND_MODAL } from "./renderAndModal.js";
import { SOCIAL_POST_UI_SCRIPT } from "../ui.js";

export const PROFILE_SCRIPT_POSTS_FEED_AND_MODAL = `
${SOCIAL_POST_UI_SCRIPT}
${PROFILE_SCRIPT_POSTS_RENDER_AND_MODAL}
${PROFILE_SCRIPT_POSTS_FEED_LOAD}
${PROFILE_SCRIPT_POSTS_INTERACTIONS}
`;
