export const APP_NAME = "Freeducation";
export const SESSION_COOKIE = "freeducation_session";
export const MAX_BODY_SIZE = 800_000;
export const SCHEMA_REVALIDATE_MS = 5 * 60 * 1000;
export const SESSION_CLEANUP_INTERVAL_MS = 60 * 1000;

export const PLATFORM_SCHEMA = {
  freeducation_admins: [
    ["id", "INTEGER PRIMARY KEY AUTOINCREMENT"],
    ["name", "TEXT NOT NULL"],
    ["email", "TEXT NOT NULL UNIQUE"],
    ["password_hash", "TEXT NOT NULL"],
    ["password_salt", "TEXT NOT NULL"],
    ["date_of_birth", "TEXT NOT NULL DEFAULT ''"],
    ["gender", "TEXT NOT NULL DEFAULT ''"],
    ["user_type", "TEXT NOT NULL DEFAULT 'Administrator'"],
    ["avatar_key", "TEXT NOT NULL DEFAULT ''"],
    ["cover_key", "TEXT NOT NULL DEFAULT ''"],
    ["created_at", "TEXT NOT NULL"],
    ["updated_at", "TEXT NOT NULL"],
  ],
  freeducation_sessions: [
    ["id", "INTEGER PRIMARY KEY AUTOINCREMENT"],
    ["admin_id", "INTEGER NOT NULL"],
    ["token_hash", "TEXT NOT NULL UNIQUE"],
    ["device_label", "TEXT NOT NULL DEFAULT ''"],
    ["active_attempt_id", "INTEGER NOT NULL DEFAULT 0"],
    ["created_at", "TEXT NOT NULL"],
    ["expires_at", "TEXT NOT NULL"],
  ],
  freeducation_social_posts: [
    ["id", "INTEGER PRIMARY KEY AUTOINCREMENT"],
    ["admin_id", "INTEGER NOT NULL"],
    ["body", "TEXT NOT NULL DEFAULT ''"],
    ["image_key", "TEXT NOT NULL DEFAULT ''"],
    ["created_at", "TEXT NOT NULL"],
    ["updated_at", "TEXT NOT NULL"],
  ],
  freeducation_social_comments: [
    ["id", "INTEGER PRIMARY KEY AUTOINCREMENT"],
    ["post_id", "INTEGER NOT NULL"],
    ["admin_id", "INTEGER NOT NULL"],
    ["parent_comment_id", "INTEGER DEFAULT NULL"],
    ["body", "TEXT NOT NULL DEFAULT ''"],
    ["created_at", "TEXT NOT NULL"],
  ],
  freeducation_social_reactions: [
    ["id", "INTEGER PRIMARY KEY AUTOINCREMENT"],
    ["post_id", "INTEGER NOT NULL"],
    ["admin_id", "INTEGER NOT NULL"],
    ["created_at", "TEXT NOT NULL"],
  ],
  freeducation_social_comment_reactions: [
    ["id", "INTEGER PRIMARY KEY AUTOINCREMENT"],
    ["comment_id", "INTEGER NOT NULL"],
    ["admin_id", "INTEGER NOT NULL"],
    ["created_at", "TEXT NOT NULL"],
  ],
  freeducation_social_mates: [
    ["id", "INTEGER PRIMARY KEY AUTOINCREMENT"],
    ["user_low_id", "INTEGER NOT NULL"],
    ["user_high_id", "INTEGER NOT NULL"],
    ["requester_id", "INTEGER NOT NULL"],
    ["receiver_id", "INTEGER NOT NULL"],
    ["status", "TEXT NOT NULL DEFAULT 'pending'"],
    ["follow_low", "INTEGER NOT NULL DEFAULT 1"],
    ["follow_high", "INTEGER NOT NULL DEFAULT 1"],
    ["created_at", "TEXT NOT NULL"],
    ["responded_at", "TEXT NOT NULL DEFAULT ''"],
    ["updated_at", "TEXT NOT NULL"],
  ],
  freeducation_social_notification_meta: [
    ["admin_id", "INTEGER PRIMARY KEY"],
    ["seen_at", "TEXT NOT NULL DEFAULT ''"],
    ["created_at", "TEXT NOT NULL"],
    ["updated_at", "TEXT NOT NULL"],
  ],
  freeducation_social_notification_reads: [
    ["id", "INTEGER PRIMARY KEY AUTOINCREMENT"],
    ["admin_id", "INTEGER NOT NULL"],
    ["notification_id", "TEXT NOT NULL"],
    ["read_at", "TEXT NOT NULL"],
    ["created_at", "TEXT NOT NULL"],
    ["updated_at", "TEXT NOT NULL"],
  ],
  freeducation_subject_templates: [
    ["id", "INTEGER PRIMARY KEY AUTOINCREMENT"],
    ["code", "TEXT NOT NULL UNIQUE"],
    ["name", "TEXT NOT NULL"],
    ["structure_json", "TEXT NOT NULL DEFAULT ''"],
    ["created_at", "TEXT NOT NULL"],
    ["updated_at", "TEXT NOT NULL"],
  ],
  freeducation_subjects: [
    ["id", "INTEGER PRIMARY KEY AUTOINCREMENT"],
    ["name", "TEXT NOT NULL"],
    ["class_id", "INTEGER NOT NULL DEFAULT 0"],
    ["class_level", "INTEGER NOT NULL"],
    ["template_id", "INTEGER NOT NULL"],
    ["thumbnail_key", "TEXT NOT NULL DEFAULT ''"],
    ["created_by", "INTEGER NOT NULL"],
    ["created_at", "TEXT NOT NULL"],
    ["updated_at", "TEXT NOT NULL"],
  ],
  freeducation_module_classes: [
    ["id", "INTEGER PRIMARY KEY AUTOINCREMENT"],
    ["name", "TEXT NOT NULL"],
    ["image_key", "TEXT NOT NULL DEFAULT ''"],
    ["show_in_home", "INTEGER NOT NULL DEFAULT 0"],
    ["sort_order", "INTEGER NOT NULL DEFAULT 0"],
    ["created_at", "TEXT NOT NULL"],
    ["updated_at", "TEXT NOT NULL"],
  ],
  freeducation_subject_nodes: [
    ["id", "INTEGER PRIMARY KEY AUTOINCREMENT"],
    ["subject_id", "INTEGER NOT NULL"],
    ["parent_node_id", "INTEGER DEFAULT NULL"],
    ["template_node_key", "TEXT NOT NULL"],
    ["server_name", "TEXT NOT NULL"],
    ["display_name", "TEXT NOT NULL"],
    ["sort_order", "INTEGER NOT NULL DEFAULT 0"],
    ["supports_chapters", "INTEGER NOT NULL DEFAULT 0"],
    ["supports_topics", "INTEGER NOT NULL DEFAULT 0"],
    ["can_edit_name", "INTEGER NOT NULL DEFAULT 1"],
    ["can_upload_image", "INTEGER NOT NULL DEFAULT 1"],
    ["image_key", "TEXT NOT NULL DEFAULT ''"],
    ["content_types_json", "TEXT NOT NULL DEFAULT '[]'"],
    ["created_at", "TEXT NOT NULL"],
    ["updated_at", "TEXT NOT NULL"],
  ],
  freeducation_subject_chapters: [
    ["id", "INTEGER PRIMARY KEY AUTOINCREMENT"],
    ["subject_id", "INTEGER NOT NULL"],
    ["node_id", "INTEGER NOT NULL"],
    ["chapter_number", "TEXT NOT NULL DEFAULT ''"],
    ["name", "TEXT NOT NULL"],
    ["topics_enabled", "INTEGER NOT NULL DEFAULT 0"],
    ["image_key", "TEXT NOT NULL DEFAULT ''"],
    ["content_types_json", "TEXT NOT NULL DEFAULT ''"],
    ["sort_order", "INTEGER NOT NULL DEFAULT 0"],
    ["created_at", "TEXT NOT NULL"],
    ["updated_at", "TEXT NOT NULL"],
  ],
  freeducation_subject_topics: [
    ["id", "INTEGER PRIMARY KEY AUTOINCREMENT"],
    ["subject_id", "INTEGER NOT NULL"],
    ["chapter_id", "INTEGER NOT NULL"],
    ["topic_number", "TEXT NOT NULL DEFAULT ''"],
    ["name", "TEXT NOT NULL"],
    ["image_key", "TEXT NOT NULL DEFAULT ''"],
    ["content_types_json", "TEXT NOT NULL DEFAULT ''"],
    ["sort_order", "INTEGER NOT NULL DEFAULT 0"],
    ["created_at", "TEXT NOT NULL"],
    ["updated_at", "TEXT NOT NULL"],
  ],
  freeducation_subject_content_items: [
    ["id", "INTEGER PRIMARY KEY AUTOINCREMENT"],
    ["subject_id", "INTEGER NOT NULL"],
    ["context_type", "TEXT NOT NULL"],
    ["context_id", "INTEGER NOT NULL"],
    ["content_type", "TEXT NOT NULL"],
    ["body", "TEXT NOT NULL DEFAULT ''"],
    ["image_key", "TEXT NOT NULL DEFAULT ''"],
    ["options_json", "TEXT NOT NULL DEFAULT '[]'"],
    ["correct_option", "TEXT NOT NULL DEFAULT ''"],
    ["sort_order", "INTEGER NOT NULL DEFAULT 0"],
    ["created_by", "INTEGER NOT NULL DEFAULT 0"],
    ["created_at", "TEXT NOT NULL"],
    ["updated_at", "TEXT NOT NULL"],
  ],
  freeducation_exam_sessions: [
    ["id", "INTEGER PRIMARY KEY AUTOINCREMENT"],
    ["user_id", "INTEGER NOT NULL"],
    ["subject_id", "INTEGER NOT NULL"],
    ["scope_type", "TEXT NOT NULL DEFAULT 'full'"],
    ["node_id", "INTEGER NOT NULL DEFAULT 0"],
    ["chapter_id", "INTEGER NOT NULL DEFAULT 0"],
    ["topic_id", "INTEGER NOT NULL DEFAULT 0"],
    ["timed", "INTEGER NOT NULL DEFAULT 0"],
    ["duration_seconds", "INTEGER NOT NULL DEFAULT 0"],
    ["question_count", "INTEGER NOT NULL DEFAULT 0"],
    ["status", "TEXT NOT NULL DEFAULT 'active'"],
    ["submitted_at", "TEXT NOT NULL DEFAULT ''"],
    ["exited_at", "TEXT NOT NULL DEFAULT ''"],
    ["created_at", "TEXT NOT NULL"],
    ["updated_at", "TEXT NOT NULL"],
  ],
  freeducation_exam_session_questions: [
    ["id", "INTEGER PRIMARY KEY AUTOINCREMENT"],
    ["session_id", "INTEGER NOT NULL"],
    ["subject_id", "INTEGER NOT NULL"],
    ["source_item_id", "INTEGER NOT NULL"],
    ["question_body", "TEXT NOT NULL DEFAULT ''"],
    ["question_image_key", "TEXT NOT NULL DEFAULT ''"],
    ["original_options_json", "TEXT NOT NULL DEFAULT '[]'"],
    ["original_correct_option", "TEXT NOT NULL DEFAULT ''"],
    ["sort_order", "INTEGER NOT NULL DEFAULT 0"],
    ["created_at", "TEXT NOT NULL"],
  ],
  freeducation_exam_attempts: [
    ["id", "INTEGER PRIMARY KEY AUTOINCREMENT"],
    ["session_id", "INTEGER NOT NULL"],
    ["user_id", "INTEGER NOT NULL"],
    ["attempt_index", "INTEGER NOT NULL DEFAULT 1"],
    ["status", "TEXT NOT NULL DEFAULT 'active'"],
    ["started_at", "TEXT NOT NULL"],
    ["expires_at", "TEXT NOT NULL DEFAULT ''"],
    ["submitted_at", "TEXT NOT NULL DEFAULT ''"],
    ["exited_at", "TEXT NOT NULL DEFAULT ''"],
    ["score", "INTEGER NOT NULL DEFAULT 0"],
    ["correct_count", "INTEGER NOT NULL DEFAULT 0"],
    ["answered_count", "INTEGER NOT NULL DEFAULT 0"],
    ["total_questions", "INTEGER NOT NULL DEFAULT 0"],
    ["timed", "INTEGER NOT NULL DEFAULT 0"],
    ["duration_seconds", "INTEGER NOT NULL DEFAULT 0"],
    ["created_at", "TEXT NOT NULL"],
    ["updated_at", "TEXT NOT NULL"],
  ],
  freeducation_exam_attempt_answers: [
    ["id", "INTEGER PRIMARY KEY AUTOINCREMENT"],
    ["attempt_id", "INTEGER NOT NULL"],
    ["session_question_id", "INTEGER NOT NULL"],
    ["question_order", "INTEGER NOT NULL DEFAULT 0"],
    ["shuffled_options_json", "TEXT NOT NULL DEFAULT '[]'"],
    ["correct_option", "TEXT NOT NULL DEFAULT ''"],
    ["selected_option", "TEXT NOT NULL DEFAULT ''"],
    ["is_correct", "INTEGER NOT NULL DEFAULT 0"],
    ["created_at", "TEXT NOT NULL"],
    ["updated_at", "TEXT NOT NULL"],
  ],
};
